export let ChallengeOffer = {
    boat_id: Number,
    cabins: Number,
    country: String,
    free_extras: String,
    guests: Number,
    id: Number,
    image_url: String,
    length: Number,
    locality: String,
    marina: String,
    model: String,
    name: String,
    price: Number,
    review_count: Number,
    review_score: Number,
    sail_type: String,
    skipper: String,
    tags: String,
    type: String,
    views_24: Number,
    year: Number,
};
